apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAME_SPACE}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: ${APP_NAME}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: ${NAME_SPACE}
  name: ${TARGET_GROUP_BINDING_NAME}
  annotations:
    elbv2.k8s.aws/healthcheck-success-codes: "200, 307"
spec:
  serviceRef:
    name: ${SERVICE_NAME}
    port: 80
  targetGroupARN: ${TARGET_GROUP_ARN}
  targetType: ip
  networking:
    ingress:
      - from:
        - securityGroup:
            groupID: ${SECURITY_GROUP_ID}
        ports:
          - port: 3000
